# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b5dc65821ab3a0bb9604ca0a314b2301bc51442970970fc2f1455cc432146c33fff5f6677b7e21275bc18fb783d408302730e7f5248e394e54e4bf8fb681ff41

test:
  secret_key_base: d2d8309f269ba05643d6dcd15931759c377bebecf2ef9720e6d8ec2c0cb5cfaf8f689f462509fcf2d9ea88cc234fda48ad2f794192a9ce29204c82f4b2573f6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
